version: '3.8'

services:

  reverse-proxy:
    image: haproxy:2.4
    restart: always
    networks:
        backend: {}
    ports:
    - "127.0.0.1:8080:8080"
    volumes:
    - ./haproxy/reverse/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:rw

  ingress-proxy:
    image: nginx:latest
    restart: always
    network_mode: host
    volumes:
    - ./nginx/ingress/default.conf:/etc/nginx/conf.d/default.conf:rw
    - ./nginx/ingress/nginx.conf:/etc/nginx/nginx.conf:rw

  web:
    container_name: web-app
    #    build:
    #   context: .
    #dockerfile: Dockerfile.python
    build:
        context: .
        dockerfile: Dockerfile.python
    image: web-app
    networks:
      backend:
        ipv4_address: 172.20.0.5
    volumes:
      - /etc/ssl/certs/yandex-ca.pem:/etc/ssl/certs/yandex-ca.pem:ro
    extra_hosts:
      - "rc1a-lup7249mt9fr6plj.mdb.yandexcloud.net:192.168.10.6"
    environment:
      DB_HOST: "rc1a-lup7249mt9fr6plj.mdb.yandexcloud.net"
      DB_USER: "app_user"
      DB_PASSWORD: "Rm2014!!"
      DB_NAME: "app_database"
    restart: always
    dns:
      - 127.0.0.53
      - 8.8.8.8
networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
